
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jan 17 15:25:58 CET 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GTEQ = 37;
  public static final int LBRACKET = 10;
  public static final int CONST = 5;
  public static final int NUMCONST = 49;
  public static final int LPAREN = 12;
  public static final int SEMI = 6;
  public static final int CONTINUE = 21;
  public static final int FOLLOW = 25;
  public static final int LSEQ = 35;
  public static final int MINUS = 30;
  public static final int DECL = 7;
  public static final int RPAREN = 13;
  public static final int AND = 29;
  public static final int LS = 34;
  public static final int OR = 28;
  public static final int COMMA = 8;
  public static final int CLASS = 11;
  public static final int INC = 26;
  public static final int DIV = 40;
  public static final int PLUS = 38;
  public static final int IF = 15;
  public static final int THIS = 44;
  public static final int DOT = 24;
  public static final int EOF = 0;
  public static final int RETURN = 22;
  public static final int RBRACKET = 9;
  public static final int NEW = 31;
  public static final int error = 1;
  public static final int MUL = 39;
  public static final int MOD = 41;
  public static final int IDENT = 50;
  public static final int BREAK = 17;
  public static final int VOID = 14;
  public static final int EQ = 32;
  public static final int COL = 45;
  public static final int FOREACH = 19;
  public static final int LBRACE = 3;
  public static final int ELSE = 20;
  public static final int ENUM = 46;
  public static final int READ = 23;
  public static final int CHARCONST = 47;
  public static final int WHILE = 16;
  public static final int RBRACE = 4;
  public static final int BOOLCONST = 48;
  public static final int EXTENDS = 42;
  public static final int PROG = 2;
  public static final int DEC = 27;
  public static final int GT = 36;
  public static final int DO = 43;
  public static final int PRINT = 18;
  public static final int NOTEQ = 33;
}

